// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_senior_hacker = "CgkIoLHz1ooREAIQDA"; // <GPGSID>
        public const string achievement_more_bits_than_elon_musk = "CgkIoLHz1ooREAIQCA"; // <GPGSID>
        public const string achievement_tapping_begginer = "CgkIoLHz1ooREAIQAQ"; // <GPGSID>
        public const string achievement_i_got_coins__but_at_what_cost = "CgkIoLHz1ooREAIQDg"; // <GPGSID>
        public const string achievement_getting_bits = "CgkIoLHz1ooREAIQBA"; // <GPGSID>
        public const string achievement_the_power_of_love = "CgkIoLHz1ooREAIQEQ"; // <GPGSID>
        public const string leaderboard_score = "CgkIoLHz1ooREAIQAA"; // <GPGSID>
        public const string achievement_i_can_feel_the_power = "CgkIoLHz1ooREAIQDw"; // <GPGSID>
        public const string achievement_a_billion = "CgkIoLHz1ooREAIQBw"; // <GPGSID>
        public const string achievement_a_pretty_short_credits = "CgkIoLHz1ooREAIQEA"; // <GPGSID>
        public const string achievement_my_first_skin = "CgkIoLHz1ooREAIQCQ"; // <GPGSID>
        public const string achievement_a_million = "CgkIoLHz1ooREAIQBg"; // <GPGSID>
        public const string achievement_tutorial_completed = "CgkIoLHz1ooREAIQEg"; // <GPGSID>
        public const string achievement_my_first_mission = "CgkIoLHz1ooREAIQCg"; // <GPGSID>
        public const string achievement_shopping = "CgkIoLHz1ooREAIQAg"; // <GPGSID>
        public const string achievement_begginer_hacker = "CgkIoLHz1ooREAIQCw"; // <GPGSID>
        public const string achievement_more_and_more_bits = "CgkIoLHz1ooREAIQBQ"; // <GPGSID>
        public const string achievement_pro_hacker = "CgkIoLHz1ooREAIQDQ"; // <GPGSID>

}

